@apiurl=http://localhost:3001/api/v1
@jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODQyNzkwNTUsImV4cCI6MTc4NDMxNTA1NX0.lszmEnextYHuV5uT8mBkuPLUazxClLXeuiS62yDLMx0k6tTkPrxkcLOFi6-HlMFFTQT-tfT40x7ONSCwsy_VVg

### Register
POST {{apiurl}}/auth/register
Content-Type: application/json

{
    "email": "admin@mdd.fr",
    "pseudo": "admin",
    "password": "password"
}

### Login
POST {{apiurl}}/auth/login
Content-Type: application/json

{
    "email": "bob@example.com",
    "password": "password"
}
