@apiurl=http://localhost:3001/api/v1
@jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JieUBleGFtcGxlLmNvbSIsImlhdCI6MTc4NDk5NjMxOSwiZXhwIjoxNzg1MDMyMzE5fQ.qC6RxsICQPLnOIsMvgq7zssDWv1ZvDa__07iSUXNAC02smUAmaXC_AwO9Rq-c_CAH6FgUBwFsM2Z8hibxeqK7g

### Register
POST {{apiurl}}/auth/register
Content-Type: application/json

{
    "email": "admin@mdd.fr",
    "pseudo": "admin",
    "password": "password"
}

### Login
POST {{apiurl}}/auth/login
Content-Type: application/json

{
    "email": "bobby@example.com",
    "password": "password"
}


### /me
GET {{apiurl}}/me
Authorization: Bearer {{jwtToken}}

