@apiurl=http://localhost:3001/api/v1
@jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODQyOTQ1NzYsImV4cCI6MTc4NDMzMDU3Nn0.u9bwsxZGDmGGawsmV3y0Rs17ivZHsb2M8-s5GoP8tWDlZ_KS4Br0b8vYK3NEP7hTQRwgAfvrxe-2bmeIO6w5mg

### Register
POST {{apiurl}}/auth/register
Content-Type: application/json

{
    "email": "admin@mdd.fr",
    "pseudo": "admin",
    "password": "password"
}

### Login
POST {{apiurl}}/auth/login
Content-Type: application/json

{
    "email": "bob@example.com",
    "password": "password"
}


### /me
GET {{apiurl}}/me
Authorization: Bearer {{jwtToken}}

