@apiurl=http://localhost:3001/api/v1
@jwtToken=eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJib2JAZXhhbXBsZS5jb20iLCJpYXQiOjE3ODQ1NDA5NTksImV4cCI6MTc4NDU3Njk1OX0.29GHc8hkisjasAykXZMSKVMub562cPpRTq_MOXRUakbMhMFZg_dV6hD674sEnOmnsazhCf3gZIxpbjpUZgGq4g

### CREATE POST
POST {{apiurl}}/post
Authorization: Bearer {{jwtToken}}

{

}

### POST endpoints
GET {{apiurl}}/post/2
Authorization: Bearer {{jwtToken}}


### User feed
GET {{apiurl}}/feed
Authorization: Bearer {{jwtToken}}
